---
- name: install nginx
  yum:
    name: nginx
    state: latest
  notify:
    - started nginx

- name: Enable service nginx on reboot
  service:
    name: nginx
    enabled: yes
  notify:
    - restart nginx
