---
- name: start and enable firewalld
  service:
    name: firewalld
    state: started
  become: yes
  # debug: 
  #   msg: 'firewalld'
- name: enable firewalld
  service:
    name: firewalld
    enabled: yes
# - name: restart firewalld
#   service:
#     name: nginx
#     state: restarted
