---
# - name: check nvm
#   shell: nvm version
#   register: nvm_install_check
#   changed_when: false
#   failed_when: false

# - name: Install nvm
#   shell: >
#     curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
#   args:
#     creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
#     warn: false
#   when: nvm_install_check.stderr.find('command not found') != -1

# - name: Set node version
#   shell: >
#     source ~/.bashrc &&
#     nvm install {{ version }} &&
#     nvm use {{ version }} &&
#     nvm alias default {{ version }}
#   vars:
#     version: v12.14.1
#     executable: /bin/bash
#   when: nvm_install_check.stderr.find('command not found') != -1

- name: Install global node
  yum: 
    name: nodejs

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: Install yarn
  npm:
    name: yarn
    global: yes
