---
- name: install mariadb
  yum: 
    name: 
      - mariadb
      - mariadb-server
    state: latest
  # notify:
  #   - start mariadb
  #   - enable mariadb
- name: start mariadb
  systemd:
    state: started
    name: mariadb

- name: enable mariadb
  systemd:
    enabled: yes
    name: mariadb

- name: secure installation
  # shell: mysql_secure_installation
  shell: mysql_secure_installation | echo 'secure install'