---
- name: config firewall
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
  firewalld:
    service: http
    permanent: yes
    state: enabled
  firewalld:
    service: https
    permanent: yes
    state: enabled
