---
- hosts: JW
  roles:
    # - role: common
    #   become: yes
    # - role: nginx
    #   become: yes
    - role: mariadb
      become: yes

  tasks:
    - name: say hi
      debug:
        msg: "hi"