---
- hosts: JWSPEECH
  roles:
    - role: common
      become: yes
      
    - role: nginx
      become: yes

    - role: nodejs
      become: no

    - role: firewall
      become: no

  tasks:
    - name: say hi
      debug:
        msg: "hi"

        
