---
- hosts: JWSPEECH
  tasks: 
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      script: ../../script/deploy.sh
      args:
        executable: /bin/bash
