# centOS 7.7
- name: update epel-release
  yum:
    name:
      - epel-release
      - https://centos7.iuscommunity.org/ius-release.rpm

- name: Upgrade all yum packages ansible, except...
  yum:
    name: "*"
    state: latest
    # exclude: git*

- name: install common package
  yum:
    name:
      - git2u
      - zip
      - unzip
      - lsof
      - sshpass
      - tree
